VALID_CARD = r"(\d{4} *){4}"
VALUE_AND_TITLE = r"(\d+) (.+)"
JOIN_AS_PAYER = r"join_as_payer (.*)"
JOIN_AS_BUYER = r"join_as_buyer (.*)"
DELETE_PURCHASE = r"delete_purchase (.*)"
PURCHASE = r"purchase (.*)"
